---
- name: Configure Clock Timezone and Summertime on Cisco IOS
  hosts: switches
  connection: network_cli
  gather_facts: false
  tasks:
   #Set timezone CST and summertime
   - name: Timezome and summertime
     ios_config:
        lines:
            #Configuration commands                         
          - clock timezone CST -6
          - clock summer-time CST recurring
   #Saving the configurations on start-config
   - name: Save running-config to start-config
     ios_config:
       save_when: modified
   #Get retur output from the show commands
   - name: "Get clock configurations"
     register: get_clock_config
     ios_command:
       commands:
          - show running-config | include clock timezone
          - show running-config | include clock summer-time
          - show clock
  #Output final results on the device run and start-config. 
   - name: save output to local directory
     copy:
       content: "{{ get_clock_config.stdout }}"
       dest: /home/bob/ansible/outputs/{{inventory_hostname}}_ntp.ios
 