---
- name: test
  hosts: switches
  gather_facts: false

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
  
  tasks:
  - name: Ping the router
    cisco.ios.ios_ping:
     dest: 192.168.1.1
     count: 100

    register: output

  - name: save output to local directory
    copy:
      content: "{{ output }}"
      dest: /home/bob/ansible/outputs/{{inventory_hostname}}ping.ios