---
- name: test
  hosts: switches
  gather_facts: false

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
  
  tasks:
  - name: Ping the router
    cisco.ios.ios_ping:
     dest: 192.168.1.1
     count: 100

  - debug: 